### PR TITLE
Include paths

### PR DESCRIPTION
**Pull request by netman69**
I think this will make things compile for more people

### CODE REVIEW

**Comment by ReservedField** [comment]
Thanks and sorry about the Makefiles, I had to get that size down :)
I don't understand how you could be missing that include path - GCC includes it by default, if it was missing nothing would compile. Also seeing your issues with libusb over at python-evic I'd say there's something funny with your libs/includes configuration. Could you post the output of trying to compile evic-sdk without the extra include path? Maybe use pastebin or something as it's going to be riddled of undefined stuff.

**Comment by netman69** [comment]
No worries, it's my bad for not pulling before i modified it. Since you seem interested about python-evic, first problem I ran into was I had to install python-devel, took me stupid long to figure that out. Getting that out of the way the install goes fine but i'm running into this http://paste.dott.co.in/#b1dc8f96645a12daf4d0d1a0ea8e3c50QFkOFHzp I'm on opensuse for the record. If there was packages for py-hidapi it'd probably just need that but it's using this python cpan like stuff it seems, which I understand not a thing about :P. Don't waste yer time on it though, I'll probably get around fixing it soon since I'm kinda curious if the restarting issue is the same I encountered.

**Comment by Ban3** [comment]
@netman69 You need libusb 1.0 for the cython-hidapi. Your error comes from using 0.1.

Could you post the build output from building the SDK.

**Comment by netman69** [comment]
I have libusb-1.0 and 0.1... It's choosing to use the wrong version i guess. Tried pointing /usr/lib64/libusb.so -> /usr/lib64/libusb-1.0.so, it was pointing to the old lib, but no luck.
Here's the sdk build log: http://paste.dott.co.in/#5214f57941defe41d63a9b795554ac1aFyaLSWAW

**Comment by ReservedField** [comment]
I don't see any errors due to missing includes?
I meant the output without your patch :)

**Comment by netman69** [comment]
Ohh lol, thought something was odd about your question :P. http://paste.dott.co.in/#29b3298f9e52ad44bf9c8c565705e4d8cD9iwctx
You and Ban3 aliases?

**Comment by ReservedField** [comment]
No, I'm the author of evic-sdk and Ban3 is the author of python-evic.
Which distro are you on? Which packages did you install to get the ARM toolchain and newlib?

**Comment by netman69** [comment]
I'm on OpenSuse, taken the packages from this repos https://build.opensuse.org/project/show/home:wkazubski

**Comment by ReservedField** [comment]
Ok, let's try this. First, uninstall all the toolchain/newlib packages you installed. Then, download the precompiled Linux toolchain from [ARM GCC Launchpad](https://launchpad.net/gcc-arm-embedded) and copy the files in the archive to the appropriate folders (i.e gcc-arm-none-eabi-whatever/bin goes to /bin and so on).
Then try rebuilding, without your patch.

**Comment by ReservedField** [comment]
Sorry, just realized... install in /usr, not in /.

**Comment by netman69** [comment]
Just did that, exact same issue.

**Comment by ReservedField** [comment]
I'll take another look tomorrow (2am here). While I go and get some sleep, could you report the output of:

```
arm-none-eabi-gcc -xc -E -v - < /dev/null
```

**Comment by netman69** [comment]
Same time zone here ;) http://paste.dott.co.in/#927b79bd131843769d62ea5c9659851b59szKNsq

**Comment by ReservedField** [comment]
Try: `ln -s /usr/local/lib/gcc/arm-none-eabi/4.8.3 /usr/local/lib64/gcc/arm-none-eabi/4.8.3`
Launchpad should be a 5.2, are you sure you installed it?

**Comment by netman69** [comment]
Well... It took me a minute to realize but there's not supposed to be that stuff in /usr/local. That out of the way launchpad does pick up on the include path unlike the prebuilt packages for opensuse. Apparently I failed to remove that after an attempt to build arm-none-eabi-gcc from source (really thought I did).

**Comment by ReservedField** [comment]
So it's fixed now?

**Comment by netman69** [comment]
I still think that path belongs in the Makefile, yet it does work without using the launchpad build if I install it properly.

**Comment by ReservedField** [comment]
That path doesn't belong there. Those are standard includes and have to be pulled in by GCC, which automatically sets up the right paths for us.
(Linking is different and yes, we do specify standard paths there - that's because we're using naked ld from binutils instead of having it proxied through GCC).
If GCC doesn't include that path by itself, then the install is bad (as you said, you now installed it properly). Do you manually add the include path for stdio.h, string.h, stdlib.h, stdint.h, etc. to your Makefiles? ;)
Including the path may do more bad than good - it may let bad toolchains slip through, which could lead to hard to debug issues.

**Comment by ReservedField** [comment]
If you are still not convinced, do a simple experiment. Take the following C program:

```
#include <stdio.h>
#include <stdint.h>

int main() {
   uint8_t test = 123;
   printf("%d\n", test);
   return 0;
}
```

As you can see I included two standard headers (`stdint.h` on purpose since it was the one it couldn't find). Now compile: `gcc main.c`. Did you have to specify the paths to the standard headers for GCC to find them?

**Comment by netman69** [comment]
Aight makes sense indeed, something must be wrong with the package I used originally then. I was naively assuming gcc just took /usr/include by default, but I don't find it hard to believe they have a better system and thinking about it an embedded compiler should even avoid that path. Sorry for bothering you with this, guess it's obvious by now i'm a newbie to embedded C :P.

**Comment by ReservedField** [comment]
Each toolchain has its include path, plus different distros may have different paths, GCC gets compiled with the right path and everything's alright :)
Closing this.

**Pull request closed without merging**
