### PR TITLE
arm-none-eabi OSX compatibility

### PR DESCRIPTION
**Pull request by mpaw**

### CODE REVIEW

**Comment by ReservedField** [comment]
I'd be better to have a single, portable shell command. `tr` is of course builtin on Linux and Cygwin, so we can use it in place of `sed`. Your command is lacking the replacement for `=`: if the path ending in `/arm-none-eabi/lib` is the first one in the list you'll get an invalid `ARMGCC` path.
I propose this:

```
ifeq ($(ARMGCC),)
    ARMGCC := $(shell cd $(shell arm-none-eabi-gcc --print-search-dir | grep 'libraries' | \
        tr '=$(if $(filter Windows_NT,$(OS)),;,:)' '\n' | \
        grep -E '/arm-none-eabi/lib/?$$' | head -1)/../.. && pwd)
endif
```

Does it work on OSX?

**Comment by ReservedField** [comment]
Tested on Win and Linux, it works.
@mpaw Waiting for OSX results.

**Comment by mpaw** [comment]
It works indeed. I updated the PR.

**Comment by ReservedField** [comment]
Could you consolidate everything into a single commit? Sorry about that :)

**Comment by mpaw** [comment]
There you go

**Pull request merged**
